### ISSUE TITLE
Enforce TLSv1 with curl breaks strong protocols (TLSv1.1 / TLSv1.2)

### ISSUE THREAD

**Issue by bastei** [fguillot/picoFeed#102]
Since https://github.com/fguillot/picoFeed/commit/31a9e89d2acf0bc2d9910c3d949a625e505563b7 curl is forced to use TLSv1. If you try to load feeds from servers that only offer stronger protocols (TLSv1.1 / TLSv1.2) you get a "SSL-certificate invalid" error.

Preventing SSLv3 is a good thing. But preventing strong protocols at the same time is really bad. That's why I think this should be reverted. SSLv3 is disabled in cURL by default since 7.39.0 anyway.

**Comment by Raydiation** [comment]
Are you sure this is what is causing the invalid cert error? The value is CURL_SSLVERSION_TLSv1 which basically allows all TLS 1.x versions

**Comment by Raydiation** [comment]
See http://php.net/manual/en/function.curl-setopt.php

**Comment by Raydiation** [comment]
Also see http://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html

**Comment by mkresin** [comment]
First of all, please provide a link to the failing feed. Otherwise it is impossible for others to reproduce and understand the issue.

It sounds more or less like a certificate validation error. Hard to say without any knowledge about your environment. 

- which php version do you use?
- on which operating system?
- is it you own server or is it provided by a hosting provider?
- which hosting provider?

Maybe http://stackoverflow.com/a/16495053 solves your issue.

> SSLv3 is disabled in cURL by default since 7.39.0 anyway.

At least the curl version bundled with php for windows is way older than 7.39.0. Furthermore you should take into account, that picofeed still supports php 5.3.

**Comment by Raydiation** [comment]
BTW: @mkresin @fguillot  at some point in time we need to think about dropping 5.3 support. http://www.zend.com/en/support-center/support/php-long-term-support shows that there is no security support for 5.3 and 5.4 security support will be dropped in 2 days.

**Comment by Raydiation** [comment]
Maybe branch it out into a separate branch for 5.3, create a release and then only backport security fixes (if you want to do that ofc)

**Comment by mkresin** [comment]
As long as we do not rely on a feature of php 5.4+ I would prefer to keep 5.3 support. It's more or less the task of the server admins to update to a recent php version first, since their servers a vulnerable. 

Especially if I have a look at the statistics from http://w3techs.com/technologies/details/pl-php/5/all and https://wordpress.org/about/stats/, I doubt that it's the right time to drop php 5.3 support.

Last but not least the used php version of the mayor linux distributions:

- Debian 6 LTS (EOL February 2016): 5.3.3
- Ubuntu 12.04 (EOL April 2017):  5.3.10
- CentOS 6.6  (EOL Q2 2017/Nov. 2020): 5.3.3

Dropping the 5.3 support, because its not longer maintained, seams to be a no go for me.

**Comment by bastei** [comment]
> which php version do you use?

5.4.36

> on which operating system?

Debian Wheezy

> is it you own server or is it provided by a hosting provider?

own server

> which hosting provider?

-

> First of all, please provide a link to the failing feed.

https://blog.fefe.de/rss.xml ([results of ssllabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=blog.fefe.de))

Testscript:
```php
<?php

for($i=0;$i<=6;$i++) {
        if($i==2) continue;

        $ch = curl_init("https://blog.fefe.de");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_USERAGENT, 'CURL_SSLVERSION '.$i);
        curl_setopt($ch, CURLOPT_SSLVERSION, $i);

        if(curl_exec($ch) === false)
                echo $i.': ' . curl_error($ch);
        else
                echo $i.': works';

        echo "\n";
        curl_close($ch);
}
```
Output:
```
0: works
1: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
3: error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure
4: works
5: works
6: works
```

> It sounds more or less like a certificate validation error.

You will get `SSL certificate problem: unable to get local issuer certificate` instead of `works` if you don't trust the root certificate of cacert.org. I hope the problem is more clear now.

**Comment by mkresin** [comment]
blog.fefe.de is a really special case. First of all, the used certificate is issued for ptrace.fefe.de. This should never be accepted as a valid certificate for blog.fefe.de.

According to ssllabs.com, fefe has disabled all protocols except TLSv1.2 for his blog.

If I run the script extended with ```curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);``` on ubuntu 14.04 (php 5.5.9), I get the following (expected) output:

```
0: works
1: works
3: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version
4: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
5: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
6: works
```

Debian Wheezy ships with curl/libcurl 7.26.0-1, which shouldn't be aware of the CURLOPT_SSLVERSION 4-6 according to http://curl.haxx.se/libcurl/c/CURLOPT_SSLVERSION.html. I've no clue why ```curl_init()``` doesn't return false for you. Maybe I'm completely wrong.

Have you confirmed that php/curl returns html content for you if you use 0, 4-6?

**Comment by bastei** [comment]
> the used certificate is issued for ptrace.fefe.de. This should never be accepted as a valid certificate for blog.fefe.de

I think as blog.fefe.de is an [Altnernative Subject Name](https://en.wikipedia.org/wiki/SubjectAltName) in the certificate it should be accepted.

> Debian Wheezy ships with curl/libcurl 7.26.0-1, which shouldn't be aware of the CURLOPT_SSLVERSION 4-6

Yeah, your right, I didn't notice that. I think it handles every invalid entry as 0. That explains my output for 4 and 5.

> Have you confirmed that php/curl returns html content for you if you use 0, 4-6?

With these values I get the html content as expacted.

**Comment by mkresin** [comment]
My bad! I didn't checked the subjectAltNames.

> That explains my output for 4 and 5.

As mentioned, 6 should work as well.

It would be really helpful if you can do the packet capture and check the used TLS version with the different ```CURLOPT_SSLVERSION``` values.

**Comment by mkresin** [comment]
Arghh typo. The ```CURLOPT_SSLVERSION``` 6 should __not__ work.

**Comment by bastei** [comment]
> It would be really helpful if you can do the packet capture and check the used TLS version

I don't know what you expect here. The server only supports TLSv1.2, so for every "working" connection it is TLSv1.2 of course.

> 6 should not work

As I said, every undefined entry is ignored and default (0) is chosen instead. That's why it is working for me when using 4-6. Have a look at the sources.

---

Ok, let's have a look at the sources:
cURL 7.33: https://github.com/bagder/curl/blob/curl-7_33_0/lib/ssluse.c#L1431
cURL 7.34: https://github.com/bagder/curl/blob/curl-7_34_0/lib/ssluse.c#L1431

The problem is obviously the different behaviour when choosing 1 (CURL_SSLVERSION_TLSv1). With versions up to 7.33 cURL calls TLSv1_client_method(), which [enforces TLSv1](https://www.openssl.org/docs/ssl/SSL_CTX_new.html). Since 7.34, choosing the same parameter 1 (CURL_SSLVERSION_TLSv1), SSLv23_client_method() is called instead, which [allows SSLv3, TLSv1, TLSv1.1 and TLSv1.2](https://www.openssl.org/docs/ssl/SSL_CTX_new.html).

So, there is another problem for people with cURL < 7.24 when choosing CURLOPT_SSLVERSION = 1: Even if a server supports TLSv1.1 or TLSv1.2, the less secure protocol TLSv1 will be enforced.

With the same parameter you get a completely different output resulting in less secure connections or even errors with older cURL versions. As Wheezy is still the stable Debian version and a very popular server OS, I still recommend to revert this at least until Jessie is out.

In my opinion it would be more important to prevent ciphers suites using things like RC4 or MD5 with the help of [CURLOPT_SSL_CIPHER_LIST](http://curl.haxx.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html).

**Comment by mkresin** [comment]
> I don't know what you expect here. 

I want to know which TLS Version is used if you set ```CURLOPT_SSLVERSION``` to 1, since I'm unable to reproduce your issue either on my development system or with the windows php binaries I had tested so far.

PHP 5.3.26 (curl 7.30.0/OpenSSL 0.9.8y):
```
0: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
1: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version [TLSv1.0]
3: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version [SSLv3]
4: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
5: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
6: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
```

PHP 5.4.38 (curl 7.40.0/OpenSSL 0.9.8zd):

```
0: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
1: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
3: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version [SSLv3]
4: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
5: Unsupported SSL protocol version
6: Unsupported SSL protocol version
```

PHP 5.5.22 (curl 7.40.0/OpenSSL 1.0.1k):
```
0: works [TLSv1.2]
1: works [TLSv1.2]
3: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version [SSLv3]
4: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
5: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.1]
6: works [TLSv1.2]
```

PHP 5.6.6 (curl 7.40.0/OpenSSL 1.0.1k)
```
0: works [TLSv1.2]
1: works [TLSv1.2]
3: error:1409442E:SSL routines:SSL3_READ_BYTES:tlsv1 alert protocol version [SSLv3]
4: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.0]
5: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [TLSv1.1]
6: works [TLSv1.2]
```

The output of the "official" windows php binaries show why it's a really bad idea to enforce TLS 1.2 these days. Openssl > 0.9.8 is required for TLS 1.1 and TLS 1.2. But it isn't as widely deployed as I would expect it. For the sake of completeness, the up-to-date centos 6 of my hoster can not establish TLS 1.2 connections at all.

> Ok, let's have a look at the sources:
cURL 7.33: https://github.com/bagder/curl/blob/curl-7_33_0/lib/ssluse.c#L1431
cURL 7.34: https://github.com/bagder/curl/blob/curl-7_34_0/lib/ssluse.c#L1431

Thanks for finding this! I've set up a Debian Wheezy and could reproduce the issue. Finally the links and your explanation is the answer to what happens here. Now we could think of a proper workaround.

> So, there is another problem for people with cURL < 7.24

I assume you are talking about 7.34.

> In my opinion it would be more important to prevent ciphers suites using things like RC4 or MD5 with the help of CURLOPT_SSL_CIPHER_LIST.

If enforcing TLS 1.x already shows compatibility issues like this one, I would bet that dropping ciphers suites is more or less a minefield.

@bastei @Raydiation @fguillot 

I can imagine the following workarounds:

0. revert the commit and being prone to the poddle attack (IMHO the worst idea)

1. Set the ```CURLOPT_SSLVERSION```dependent on the [curl version](https://php.net/manual/de/function.curl-version.php). This way we could limit the vulnerability to the poddle attack to cURL < 7.34.

2. Fallback to ```CURL_SSLVERSION_DEFAULT``` if ```curl_error($ch)``` returns something like ```error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure``` (*what is the appropiate error to check for?*) and the used curl version is < 7.34.

3. Check the used SSL/TLS version after getting a response and stop if it's SSLv3 (*if anyone can figure out how this can be done!*)

**Comment by Raydiation** [comment]
Very difficult and we need proper TLS for iframes, otherwise we'll get problems with mixed active content.

Adding proper ciphers or rather blacklisting insecure ones is very important I think. Either we are secure or we aren't.

IMHO we should be maximum secure by default, so basically require TLS 1.2 and secure ciphers. If the system does not support these we should throw a special kind of exception to allow devs to react to these things.

Sure there are feeds and servers that are too old to fullfill these requirements, so there should be config options to cater to these needs. IIRC we already offer to turn off SSL cert validation. We would probably also need an option to set the required tls protocols and ciphers to insecure versions.

As for the ownCloud News app: I'll probably require a secure curl version and secure ciphers, basically ignore old setups which is basically only Debian Wheezy. For Wheezy I'll add a guide to enable repositories with recent and secure versions, probably available in the backports repo. @bastei could help me with this.

**Comment by Raydiation** [comment]
Ah right, https iframes are handled by the browser :P 

we should still enforce maximum security by default.

**Comment by mkresin** [comment]
> we should still enforce maximum security by default.

If we would have control over client _and_ server I would agree. But it isn't the case. In other words, a feed library that only works with a minority of the feeds/server isn't worth the code. We have to find a balance between security and interoperability. I expect that known totally doomed stuff like SSLv3 and RC4 is blacklisted by default. Everything else should be optional.

> IIRC we already offer to turn off SSL cert validation

Nope. Because people tend to disable validation instead of fixing their config.

> I'll probably require a secure curl version and secure ciphers, basically ignore old setups which is basically only Debian Wheezy

As outlined before, it isn't only debian wheezy. I'm at least aware of debian squeeze and centos 6. I known, it is old stuff but it's still maintained and used.

What about shared hoster, where you don't have the possibility to update any binaries? At least Miniflux is ideal to be used with shared hoster. It simply works and the users don't have to be care about the server administration.

In the end it is a simple question: For whom you're writing software. Is the answer only for you, raise the requirements as you like. Is the answer for the users, you should carefully consider what kind of requirements do you introduce.

It's the same as with crypto stuff like gnupg. Great software, good crypto but obviously way to complex for even experienced users. The result: I can send encrypted stuff, but I've no one who could receive encrypted stuff.

**Comment by Raydiation** [comment]
This is fine, miniflux can still support old installations and hosting just fine. You'd just have to add something like this to your config:

    $config->setTLSVersion(SSL::TLS1x)->whitelistCiphers([Cipher::RC4, Cipher::MD5]);

I'm not against compatibility, all I'm saying is: be secure out of the box and let devs tweak things to their likings. 

It is always hard to follow updates and an update should not rip holes into your security because you forgot to turn on a more secure mode. It is better that something fails and the dev can easily fix it than security holes going unnoticed

**Comment by Raydiation** [comment]
You could even add that to the readme like: add these config parameters if you want to support debian wheezy etc.

**Comment by mkresin** [comment]
It's more or less a question of the philosophy.

I agree that awfully broken stuff like RC4 should be irreversible blacklisted by default (similar to stripping style and script tags from content). But for anything else, it's up to the developers to blacklist stuff:

```
$config->setTLSVersion(SSL::TLS10)->disable();
```

Being maximum secure but literally non-functional without further interaction is a no go for me ;-).

**Comment by Raydiation** [comment]
Well, this is far from non-functional, this affects just one stable distro that will get a new stable release very soon ;)

It's less of a philosophy question and more a question of good API design. Also most PHP devs have no  clue about security and we need to keep that in mind.

**Comment by mkresin** [comment]
> Well, this is far from non-functional, this affects just one stable distro that will get a new stable release very soon ;)

It's not about stable releases, it's about supported releases. I don't know how familiar you are with server administration but at least I don't (and I don't know any sysadmin who) update the server os without any need, as long as the current version is still supported. You know, never touch a running system. Otherwise you have to check the used packages for new/changes features, updating configuration, do compatibility tests and updating documentation and so on.

Just to illustrate (my) the real world situation:

- hosteurope.de, which is one of the biggest german hosting providers, uses debian squeeze LTS for their webpack product
- uberspace.de (one of the coolest provider ever btw.) uses centos 6 on their servers

Now I count three widely used and still supported distribution that have their problems with TLSv1.2 for example. That's what I'm talking about.

Disclamer ;-): This isn't meant as offence. Hopefully it does not read as.

**Comment by fguillot** [comment]
I'm late on this thread, but for me this library must work on all active LTS distros.

The solution 2 seems to be the most simple to implement?

> Set the CURLOPT_SSLVERSION dependent on the curl version. This way we could limit the vulnerability to the poddle attack to cURL < 7.34.

**Comment by bastei** [comment]
> Check the used SSL/TLS version after getting a response and stop if it's SSLv3

That would be the best solution. Unfortunately I'm not aware of any method how to do that... unless [PHP 5.6](http://docs.php.net/manual/en/migration56.openssl.php#migration56.openssl.metadata) is used.

> If enforcing TLS 1.x already shows compatibility issues like this one, I would bet that dropping ciphers suites is more or less a minefield.

I think you are wrong here. If I don't misinterpret the curl sources it passes the ciphers to openssl without modifying anything. So in contrast to the SSL protocols you have the full power over the parameters here.

Therefore, we could think about something like this as a potential workaround:
```php
<?php
function curl($sslver, $ciphers) {
        $ch = curl_init("https://example.com");
        curl_setopt($ch, CURLOPT_NOBODY, true);

        curl_setopt($ch, CURLOPT_SSLVERSION, $sslver);
        curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, $ciphers);

        $result = curl_exec($ch);
        curl_close($ch);
        return ($result === false) ? false : true;
}

$goodcurl = (curl_version()['version_number'] >= 467456); // curl >= 7.34

if ( curl(0, "DEFAULT:!SSLv2:!SSLv3") ) {
        echo "connected via TLSv1.2\n";
        exit;
}
if( curl(1, "HIGH:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK") ) {
        if($goodcurl)   echo "connected via TLSv1, TLSv1.1 or TLSv1.2\n";
        else            echo "connected via TLSv1\n";
        exit;
}
if( !$goodcurl && curl(0, "HIGH:!aNULL:!eNULL:!EXPORT:!DSS:!DES:!RC4:!3DES:!MD5:!PSK") ) {
        echo "certainly connected via SSLv3, maybe TLSv1.1. TLSv1.2 is very unlikely\n";
        exit;
}
if( curl(0, "DEFAULT") ) {
        echo "connected via SSLv3 or with weak ciphers\n";
        exit;
}
echo "Better don't contact that server...";
```
Explanation: To get the best encryption, we try to connect with gradually decreasing encryption strength:

1. **Only TLSv1.2 ciphers**. This enforces the TLSv1.2 protocol.

2. **Strong ciphers and TLSv1, TLSv1.1 and TLSv1.2** for curl >= 7.34. Old versions will be forced to TLSv1. We can't test TLSv1.1 for them, but I think most of the servers with TLSv1.1 have support for TLSv1.2, too (and thus the first test would probably be successful).

3. Do an **extra test for old curl versions**, **all protocols** allowed, but only **good ciphers**. There is the possibility for combinations that don't fall under 1. and 2. but that work here, for example servers with TLSv1.2 protocol only but no TLSv1.2 ciphers or TLSv1.1 protocol only, even if I think these scenarios are very unlikely. The worst case here is SSLv3, but with good ciphers (which is absolutely not unlikely).

4. Default protocol, default ciphers. This is a fallback where only **SSLv3 or bad ciphers** are left. You can leave this out and throw an error.

Note that the main trick is using the TLSv1.2 ciphers to test TLSv1.2 support. It is also possible to use "DEFAULT" ciphers in 2. and then leave 3 if you don't want to mess around with ciphers too much.

**Comment by mkresin** [comment]
> I think you are wrong here. If I don't misinterpret the curl sources it passes the ciphers to openssl ...

What I mean with minefield is that libcurl isn't necessary compiled against openssl. On the mentioned contos 6 host, libcurl is compiled against NSS.

```
curl
cURL support 	enabled
cURL Information 	7.19.7
Age 	3
Features
AsynchDNS 	No
CharConv 	No
Debug 	No
GSS-Negotiate 	Yes
IDN 	Yes
IPv6 	Yes
krb4 	No
Largefile 	Yes
libz 	Yes
NTLM 	Yes
SPNEGO 	No
SSL 	Yes
SSPI 	No
Protocols 	tftp, ftp, telnet, dict, ldap, ldaps, http, file, https, ftps, scp, sftp
Host 	x86_64-redhat-linux-gnu
SSL Version 	NSS/3.16.2.3 Basic ECC
ZLib Version 	1.2.3
libSSH Version 	libssh2/1.4.2 
``` 

Does it work the same way here? How does the other supported ssl libraries (http://curl.haxx.se/docs/ssl-compared.html) behave.

> 3. Fallback to CURL_SSLVERSION_DEFAULT if curl_error($ch) returns something like error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure (what is the appropiate error to check for?) and the used curl version is < 7.34.

Answering my own question: Won't work. The errormessage depends on the used ssl library.

**Comment by mkresin** [comment]
After reading your reply once again and under the premise that all by libcurl supported libraries behave the same (which is questionable according to http://stackoverflow.com/a/26764845), the following:

```
curl_setopt($ch, CURLOPT_SSLVERSION, 1)
```

should be equivalent to

```
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, "DEFAULT:!SSLv2:!SSLv3") 

```


> Unfortunately I'm not aware of any method how to do that... unless PHP 5.6 is used.

And even this shouldn't work with curl. As far as I can see it's for the the [Stream Context http client adapter](http://php.net/manual/de/function.stream-context-create.php) and not for cURL.

But that leads me to another question: How to enforce TLS 1.x if the Stream Context http client adapter is used. As far as I know, openssl is used here always.

The ```ciphers``` options of http://php.net/manual/de/context.ssl.php looks suitable. Can anyone confirm that "DEFAULT:!SSLv2:!SSLv3" should do the trick?

**Comment by bastei** [comment]
> What I mean with minefield is that libcurl isn't necessary compiled against openssl.

Ok, could be a problem... What is your output for `print_r(curl_version());` ?

---

> Can anyone confirm that "DEFAULT:!SSLv2:!SSLv3" should do the trick?

No, "DEFAULT:!SSLv2:!SSLv3" is the same as "TLSv1.2:!eNULL:!aNULL".

See the NOTES-section of https://www.openssl.org/docs/ssl/SSL_CIPHER_get_name.html#NOTES:

> The TLSv1.0 ciphers are flagged with SSLv3. No new ciphers were added by TLSv1.1.

Basically, SSLv3 ciphers are all DEFAULT ciphers minus the TLSv1.2 ciphers. Nevertheless, you can connect via TLSv1.2 protocol but with SSLv3 ciphers.

---

> How to enforce TLS 1.x if the Stream Context http client adapter is used.

I tried it and failed. It is the same problem as with curl for me: Using `STREAM_CRYPTO_METHOD_TLS_CLIENT` enfores TLSv1, `STREAM_CRYPTO_METHOD_SSLv23_CLIENT` allows SSLv3.

**Comment by mkresin** [comment]
> What is your output for print_r(curl_version());

```
Array
(
    [version_number] => 463623
    [age] => 3
    [features] => 1597
    [ssl_version_number] => 0
    [version] => 7.19.7
    [host] => x86_64-redhat-linux-gnu
    [ssl_version] => NSS/3.16.2.3 Basic ECC
    [libz_version] => 1.2.3
    [protocols] => Array
        (
            [0] => tftp
            [1] => ftp
            [2] => telnet
            [3] => dict
            [4] => ldap
            [5] => ldaps
            [6] => http
            [7] => file
            [8] => https
            [9] => ftps
            [10] => scp
            [11] => sftp
        )
```

> No, "DEFAULT:!SSLv2:!SSLv3" is the same as "TLSv1.2:!eNULL:!aNULL".

Thanks for the explanation. As you might already know, I've mixed up protocol and protocol cypher suits. My bad.


> I tried it and failed. It is the same problem as with curl for me: Using STREAM_CRYPTO_METHOD_TLS_CLIENT enfores TLSv1, STREAM_CRYPTO_METHOD_SSLv23_CLIENT allows SSLv3. 

Okay, no need for me to try it again.

**Comment by mkresin** [comment]
I've opened https://github.com/fguillot/picoFeed/pull/104 which disables SSLv3 for known good libcurl version.

If anyone has better solution, feel free to send a superseding patch.

**Comment by fguillot** [comment]
@bastei can you confirm that the issue is solved by the pull-request of @mkresin ?

**Comment by bastei** [comment]
@fguillot @mkresin 
It works. Thanks for the fast fix and good discussion! :+1:
