### ISSUE TITLE
Missing RSS Element?

### ISSUE THREAD

**Issue by rbrecht** [fguillot/picoFeed#103]
Are there any reasons, why there is no method for $feed->ttl ? 
http://www.w3schools.com/rss/rss_tag_ttl.asp

or the other optional fields defined in the specs?
http://www.w3schools.com/rss/rss_reference.asp

for example, you use the optional field "enclosure", but you dont use "guid". 

Would be nice, to have all methods for all possible fields

**Comment by Raydiation** [comment]
See http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared

    <ttl> is problematic, prefer HTTP 1.1 cache control

the ttl element is only part of RSS and not Atom. Since RSS and Atom are served over HTTP, HTTP caching is the preferred solution.

**Comment by Raydiation** [comment]
Also see http://www.rssboard.org/rss-profile#element-channel-ttl

    The following aggregators ignore this element: BlogBridge, Bloglines, Google Reader, JetBrains Omea, Mozilla Firefox, My Yahoo, NewsGator Online and RSSBandit.

**Comment by rbrecht** [comment]
so, the best practise is to fetch all the feeds every x minutes, and check for new content? 
I'm fine if the ignore this element, but what if someone needs this or other elements like guid as described? You are just limiting your software by not using all the elements defined by the specification ;)
Just my 2 cents... Still like picoFeed, but I will have to modify it for all of my needs :/

**Comment by mkresin** [comment]
> so, the best practise is to fetch all the feeds every x minutes, and check for new content? 

Nope. The best practice is to fetch the feeds every x minutes and evaluate the caching headers as described in https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown#http-caching.

> but you dont use "guid". 

picofeed returns an id for every item https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown#feed-and-item-properties. This id is either based on the GUID or if no GUID exists, on a combination of article title, article url and article preview from the feed to generate the id (https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Parser/Atom.php#L223).

It is simply abstracted for you, since not all items have an id.

> I'm fine if the ignore this element, but what if someone needs this or other elements like

(s)he is invited to send a pull request. It doesn't make sense to add functionally/code that nobody uses at the moment.

**Comment by Raydiation** [comment]
RSS spec says the only elements that are actually required are title, link and description.

**Comment by mkresin** [comment]
> Still like picoFeed, but I will have to modify it for all of my needs

Feel free to ask for a particular functionality. A lot of stuff is already implemented. Maybe it isn't obvious how to use it

Furthermore you can have a look at https://github.com/miniflux/miniflux or https://github.com/owncloud/news which both use picofeed.

**Comment by rbrecht** [comment]
Thanks for your help and informations. 
Issue can be closed.

I'll add a question/issue about the opml importer in the next days ;)

**Comment by Phyks** [comment]
This issue is really interesting, since I had the same issue. Maybe a summary of it should go in the doc? Would be easier than looking into the issues :)

**Comment by Phyks** [comment]
Some other elements are missing (this is what I found diff-ing with the specs):

* `description` (which is not the same as content). Take for instance an RSS item, it has a `description` tag but can also have a `content:encoded` tag. picoFeed returns the content from the `content:encoded` thus discarding the `description`. (Atom has similar feature through `summary` and `content`).

* Same thing for enclosure, although this is unclear about RSS (but Wordpress and others already allow it), Atom explicitly says that multiple enclosures can be inclduded in a single entry. But it seems picoFeed can only fetch one?

* Atom support multiple links in a single entry. RSS has a `comments` (Atom uses a `link` tag) tag linking to the page with the comments on this article. These `comments` links can be considered as extra links too.

* Publication and last update date are not reflected in the API.

* Atom (contrary to RSS) supports multiple authors, which are not reflected in the API.

Are there some specific reasons for the lack of some tags? (apart from the `ttl` tag originally discussed). Especially since these are supported by both Atom and RSS and are part of the specs.

Thanks

**Comment by BernhardPosselt** [comment]
@Phyks Most of your "missing" API features are actually irrelevant for feed readers and therefore not explicitely (as in: a bit more type safe) exposed in the API. The problem feed aggregators have is that you need a common ground, which is what picoFeed currently offers. 

If you think this is not sufficient when building a feed reader, you can of course suggest alternatives and provide reasons why it should be implemented. However it seems that you are simply trying to parse an Atom feed, so picoFeed may not be what you want. 

However you can select all the attributes that you are mentioning by using a more generic and less type safe API, see https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown#get-raw-xml-tagsattributes-or-non-standard-tags-for-items

On a side note: your issue is different from OP's issue, please open a new issue the next time ;)

**Comment by Phyks** [comment]
@BernhardPosselt Sorry for having posted in this issue, as the title was simply "Missing RSS element", I thought it was generic enough. This is done https://github.com/fguillot/picoFeed/issues/228.
