### ISSUE TITLE
Validate charset

### ISSUE THREAD

**Issue by alextyrey** [fguillot/picoFeed#111]
```exception 'ErrorException' with message 'iconv(): Wrong charset, conversion from `text/html' to `UTF-8//IGNORE' is not allowed' in /srv/http/pulsefeed/releases/20150317183846/vendor/fguillot/picofeed/lib/PicoFeed/Encoding/Encoding.php:19```

When using the content grabber, it's not uncommon to run into this. Maybe validating the reported charset would be a good idea?

**Comment by mkresin** [comment]
Would you please provide a real world example, so that I can have a look what's going on there.

A reliable guessing of an encoding is nearly impossible. And to be honest, if a website reports that it's using encoding A but the content is encoded B, the website is simply defect. That should be fixed instead of applying a half-baked workaround.

We had this discussion already at https://github.com/fguillot/picoFeed/pull/91#issuecomment-74413234.

**Comment by alextyrey** [comment]
http://www.cnn.com/2015/03/18/health/breastfeeding-iq-income/index.html

I agree that the website should fix it instead of relying on a "half-baked workaround". However, I wouldn't consider the validation of data to be "half-baked" or even a "workaround". Just my 2 cents.

**Comment by mkresin** [comment]
A validation is neither a workaround nor half-baked. But all ways I'm aware of doing the validation are "half-baked".

Yeah, it would be possible to catch the mentioned exception. But what should be returned in that case?

Anyway, it looks like you found a bug. The page is utf8 encoded and has the matching ```<meta charset="utf-8">```. But instead of using this meta tag, picoFeed uses ```<meta content="text/html"...```. And text/html is not a charset at all.

I will have a look at the code later.

**Comment by alextyrey** [comment]
Thanks @mkresin. :)

**Comment by mkresin** [comment]
The related commit is https://github.com/fguillot/picoFeed/commit/9be2748dbba31b729067fec9e0ffe69b719359fd.

I'm busy the next days, so if anyone has the time to fix this, do it!

**Comment by mkresin** [comment]
@alextyrey would you please test https://github.com/mkresin/picoFeed/commit/00794f553b1097b730f8bb02c492b43c82c60167. Since regular expressions are always a bit tricky, a review is highly welcome.

**Comment by alextyrey** [comment]
At a glance, that expression looks like it should do the trick.

I'll reply back tomorrow. Gonna let it run with a couple hundred sources. :)

**Comment by alextyrey** [comment]
Looks good @mkresin! Zero exceptions since I've implemented your patch.

:+1: to merge.
