### ISSUE TITLE
How to disable ssl cert check if auto-signed

### ISSUE THREAD

**Issue by claudyus** [fguillot/picoFeed#117]
Hi all,

how I can disable the ssl certificate chec if the certificate is auto-signed

I read something here [1] but I was enable to find docs about if in Config class.

1. https://github.com/fguillot/picoFeed/issues/59

error log:
```
exception 'PicoFeed\Client\InvalidCertificateException' with message 'Invalid SSL certificate' in /home/cmignanti/code/georss-merger/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php:406
Stack trace:
#0 /home/cmignanti/code/georss-merger/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php(285): PicoFeed\Client\Curl->handleError(60)
#1 /home/cmignanti/code/georss-merger/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php(303): PicoFeed\Client\Curl->executeContext()
#2 /home/cmignanti/code/georss-merger/vendor/fguillot/picofeed/lib/PicoFeed/Client/Client.php(213): PicoFeed\Client\Curl->doRequest()
#3 /home/cmignanti/code/georss-merger/vendor/fguillot/picofeed/lib/PicoFeed/Reader/Reader.php(75): PicoFeed\Client\Client->execute('https://owm1.un...')
#4 /home/cmignanti/code/georss-merger/index.php(31): PicoFeed\Reader\Reader->download('https://owm1.un...', '', '', 'user', 'pass;...')
#5 [internal function]: {closure}()
#6 /home/cmignanti/code/georss-merger/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#7 /home/cmignanti/code/georss-merger/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#8 /home/cmignanti/code/georss-merger/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /home/cmignanti/code/georss-merger/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /home/cmignanti/code/georss-merger/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#11 /home/cmignanti/code/georss-merger/vendor/slim/slim/Slim/Slim.php(1302): Slim\Middleware\PrettyExceptions->call()
#12 /home/cmignanti/code/georss-merger/index.php(139): Slim\Slim->run()
```

**Comment by Raydiation** [comment]
The config option is missing it seems. 

As for your problem: if you are required to support a self signed cert, it's better to import it to the installed certs rather than turning off the checks for everything else and opening yourself up to MITM attacks.

Check the last answer on this page http://stackoverflow.com/questions/5109661/add-self-signed-certificate-to-ubuntu-for-use-with-curl

**Comment by mkresin** [comment]
It's not possible at the moment and my personal point of view is, that it shouldn't be possible. And because I take your security serious, I do not even show you the place within the code to disable certificate verification.

If someone can read your unencrypted traffic, it's an easy game to do a man in the middle attack if you use SSL without certificate verification. Long story short, disabling certificate verification is exactly secure as doing http requests unencrypted.

startssl.com for example issues ssl certificates for free. Another possibility is to setup your own Certificate Authority and import this CA certificate to your trusted CA certificates.

**Comment by claudyus** [comment]
If someone else need the quick and dirty fix

```
diff --git a/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php b/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php
index 278eeb4..89f9b8e 100644
--- a/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php
+++ b/vendor/fguillot/picofeed/lib/PicoFeed/Client/Curl.php
@@ -242,6 +242,8 @@ class Curl extends Client
         curl_setopt($ch, CURLOPT_ENCODING, '');
         curl_setopt($ch, CURLOPT_COOKIEJAR, 'php://memory');
         curl_setopt($ch, CURLOPT_COOKIEFILE, 'php://memory');
+        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
+        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
 
         // Disable SSLv3 by enforcing TLSv1.x for curl >= 7.34.0 and < 7.39.0.
         // Versions prior to 7.34 and at least when compiled against openssl
```

**Comment by mkresin** [comment]
@claudyus It is not even a qick'n'dirty fix, it's a big security hole!

I'm not sure if you didn't understand what I've written or you simply do not care about security.

To make my point clear once more: If you disable the peer/host validation, you do not need any encryption. Using unencrypted HTTP in that case, is your quick'n'dirty fix.

@fguillot Would you please remove  to comment above! It's obviously that we need to protect the users from themselves

**Comment by Raydiation** [comment]
Maybe we should add a FAQ section that discusses this issue and provides a link or description how to add self signed certs.

**Comment by claudyus** [comment]
@mkresin it is just an hack to resolve the my ssl problem when I fetch info from a server configured as https (by another team) and I should retrieve those information inside aipsec lan. I pretty sure that in this situation I can relax my checks.
Feel free to remove the comment if it is so "dangerous"

**Comment by mkresin** [comment]
>  it is just an hack to resolve the my ssl problem 

@claudyus You named it a quick and dirty fix. That could be misleading to other people with the same problem. They could suspect an fixable error in picoFeed rather than a - normally - easy fixable configuration problem with their PHP installation. That's my problem with your solution.

Am I right, that your verified that it's really a self signed certificate? Especially with php on windows you have to do some additional steps to successful verify even "officially" signed certificates.

Have you every tried to ask the other team for the CA Certificate that signed the remote servers certificate?

I'm still interested in fixing your setup rather than disabling security related settings.

**Comment by zelenin** [comment]
```php
$response = $client->get($url); // guzzle
$body = (string)$response->getBody();

$reader = new Reader();
$parser = $reader->getParser($feed->url, $body, 'utf-8');

$data = $parser->execute();
```
3rd party client workflow with disabled ssl cert check.

**Comment by Raydiation** [comment]
@fguillot we should probably lock the issue :)

@zelenin please don't use that, just download the cert and add it to your trusted certs or add a startssl/letsencrypt/wosign cert

**Comment by Raydiation** [comment]
We should probably add self signed cert best practices to the docs btw
