### ISSUE TITLE
Exception : XML parsing error

### ISSUE THREAD

**Issue by emmanuelroecker** [fguillot/picoFeed#138]
Hi,

I've an exception "XML Parsing Error" with this rss feed : http://www.lyoncapitale.fr/layout/set/rsslayout/googlesitemap/rss/actualitelyon.

Have you an idea ?

Best regards

**Comment by mkresin** [comment]
The parsing error is related to the ```<!ENTITY nbsp "&#160;">``` tag at line 2 of the feed. This tag is sanitized by picofeed, because it can be used for local and remote file inclusion attacks [[1]](http://php.net/manual/de/function.libxml-disable-entity-loader.php#107730).

As soon as picofeed detects this tag, the feed is considered as invalid. I don't know why this tag is used within the feed, since it doesn't include anything.

Furthermore, the feed is in the RSS format, but uses the atom namespace and atom:link. This is bogus, but not problematic for picofeed.

Please contact the feed creators to fix the outlined errors and point them to the [W3C feed validator](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.lyoncapitale.fr%2Flayout%2Fset%2Frsslayout%2Fgooglesitemap%2Frss%2Factualitelyon). The feed has a few more issues, which will prevent that images are displayed within feed readers.

**Comment by emmanuelroecker** [comment]
Ok

Thank you very much !!
