### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() in Parser\Parser.php on line 153

### ISSUE THREAD

**Issue by acrozes** [fguillot/picoFeed#152]
bin/picofeed feed http://www.tv5.org/TV5Site/rss/actualites.php?rub=18

PHP Warning:  Invalid argument supplied for foreach() in vendor\fguillot\picofeed\lib\PicoFeed\Parser\Parser.php on line 153

Warning: Invalid argument supplied for foreach() in vendor\fguillot\picofeed\lib\PicoFeed\Parser\Parser.php on line 153

Feed::id = http://www.tv5monde.com/TV5Site/rss/actualites.php?rub=18
Feed::title = http://www.tv5monde.com
Feed::feed_url = http://www.tv5monde.com/TV5Site/rss/actualites.php?rub=18
Feed::site_url = http://www.tv5monde.com
Feed::language =
Feed::description =
Feed::logo =
Feed::date = Tue, 12 May 15 16:14:23 +0000
Feed::isRTL() = false
Feed::items = 0 items

**Comment by mkresin** [comment]
Well, the [feed validator](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.tv5monde.com%2FTV5Site%2Frss%2Factualites.php%3Frub%3D18) says the URL isn't a valid feed.

Since the feed is malformed/invalid, it's okay that picofeed issues a PHP warning and this isn't a bug at all.

What do you think? Or did I missed the point of your bug report?

**Comment by fguillot** [comment]
The feed is not valid but that should not generate php warnings.
