### ISSUE TITLE
RSS Parser: Accessing multiple identical tag in item ?

### ISSUE THREAD

**Issue by acrozes** [fguillot/picoFeed#170]
In this feeds samples:
 - http://feeds.feedburner.com/people/stylewatch/offtherack
 - http://stylenews.peoplestylewatch.com/feed/

There is multiple "media:content" tags in items.

To get the first: 
$item->getTag('media:content', 'url');

How can I get the others 'media:content' url ?

Thx

**Comment by Raydiation** [comment]
ATM you need to solve this by accessing the xml itself (simple_xml), e.g.

    $item->xml;

https://github.com/fguillot/picoFeed/blob/master/lib/PicoFeed/Parser/Item.php#L128

To solve this properly the method should IMHO be refactored so that it does not take an attribute value and that it does not cast the node to a string so you get the raw simplexml tag or taglist and can act on that on your own.

e.g.:
```php
    public function getTag($tag)
    {
        // Get namespaced value
        if (strpos($tag, ':') !== false) {
            list(,$tag) = explode(':', $tag);
            return XmlParser::getNamespaceValue($this->xml, $this->namespaces, $tag);
        }
        // Return tag 
        return $this->xml->$tag;
    }
```

**Comment by acrozes** [comment]
A new method 
```
     public function getTags($tag)
```
should be introduice and return an array of values.
And this new method need also a new method from XmlParser class ? 
```
XmlParser::getNamespaceValues(...)
```

**Comment by Raydiation** [comment]
Another possibility would also be to scrap the method altogether and let users operate on the simple xml for full flexibility which seems appropriate since this is an edge use case

**Comment by mkresin** [comment]
@acrozes The ```getTag()``` function returns an array of values with the latest picofeed development version. Please check the updated documentation.

Please close the ticket if it works for you!
