### ISSUE TITLE
How to parse content in string (not by url)

### ISSUE THREAD

**Issue by rakshazi** [fguillot/picoFeed#250]
Hello!
I need to parse atom feed in string (and grab items from it), how can I do this?

Example (pseudo-code):

```php
<?php
$reader = new \picoFeed\Reader\Reader;
$content = ATOM_XML_FEED_CONTENT;
/** @var \picoFeed\Parser\Feed $feed */
$feed = $reader->loadString($content);
```

**Comment by rakshazi** [comment]
@fguillot @BernhardPosselt  can you help me with this, please?

**Comment by BernhardPosselt** [comment]
Check https://github.com/fguillot/picoFeed/blob/master/docs/feed-parsing.markdown

It's basically exactly the same as example, but without the download. You only need to pass the correct content to the parser (instead of using  $resource->getContent()) and the url (which is needed for various filters).

**Comment by rakshazi** [comment]
@BernhardPosselt thank you! It works
